futeboladas/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'futeboladas'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('profile/<str:pk>', login_required(views.ProfileView.as_view()), name='profile'),
    path('manage_profile/', views.manage_profile, name='manage_profile'),
    path('create_game/', views.create_game, name='create_game'),
    path('games/', login_required(views.GamesListView.as_view()), name='games'),
    path('games/<str:pk>/', views.game_detail, name='game_detail'),
    path('friends/', views.friends, name='friends'),
]

futeboladas_app/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('futeboladas.urls')),
]

game_planner_app/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'game_planner_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('players/', views.PlayersListView.as_view(), name='players'),
    path('profile/<str:pk>', views.ProfileView.as_view(), name='profile'),
    path('manage_profile/', views.manage_profile, name='manage_profile'),
    path('create_game/', views.create_game, name='create_game'),
    path('games/', login_required(views.GamesListView.as_view()), name='games'),
    path('games/<str:pk>/', views.game_detail, name='game_detail'),
    path('manage_game/<str:pk>/', views.manage_game, name='manage_game'),
    path('friend_requests/', views.friend_requests, name='friend_requests'),
    path('notification_read/', views.notification_read, name='notification_read'),
    path('mark_all_as_read/', views.mark_all_as_read, name='mark_all_as_read'),
    path('manage_participation/', views.manage_participation, name='manage_participation'),
]

game_planner_app/models.py
from datetime import date, datetime
from enum import Enum

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

def pkgen(stringLength=12):
    import random
    import string

    lettersAndDigits = string.ascii_lowercase + string.digits
    return ''.join(random.choice(lettersAndDigits) for i in range(stringLength))

class Player(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    friends = models.ManyToManyField("self", null=True, blank=True)
    number_of_games_played = models.IntegerField(default=0)

    def __str__(self):
        string = self.user.username
        return string

    def get_absolute_url(self):
        return "/profile/%i" % self.user.id

class Game(models.Model):
    game_id = models.CharField(primary_key=True, max_length=12, editable=False)
    name = models.CharField(max_length=30)
    admin = models.ForeignKey(User, on_delete=models.CASCADE, related_name='game_admin')
    when = models.DateTimeField()
    where = models.CharField(max_length=60)
    players = models.ManyToManyField(Player)
    price = models.IntegerField()
    duration = models.DurationField()
    private = models.BooleanField(default=False)

    def __str__(self):
        return str(self.when) + " - " + self.name

    def get_absolute_url(self):
        return "/games/%s/" % self.game_id
    
    def get_manage_url(self):
        return "/manage_game/%s/" % self.game_id

    def is_in_the_future(self):
        return self.when.replace(tzinfo=None) > datetime.now()

class NotificationType(Enum):
    FRIEND_REQ = 0
    PARTICIPATION_REQ = 1
    ADDED_AS_FRIEND = 2
    ADDED_TO_GAME = 3

class Notification(models.Model):
    notification_type = models.IntegerField()
    creation_datetime = models.DateTimeField()
    read_datetime = models.DateTimeField(null=True, blank=True)
    read = models.BooleanField(default=False)
    sender = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, related_name='sender')
    game = models.ForeignKey(Game, on_delete=models.CASCADE, null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user')

class FriendRequest(models.Model):
    request_from = models.ForeignKey(Player, on_delete=models.CASCADE, related_name='friend_request_from')
    request_to = models.ForeignKey(Player, on_delete=models.CASCADE, related_name='friend_request_to')
    request_datetime = models.DateTimeField()
    action_taken_datetime = models.DateTimeField(null=True, blank=True)
    state = models.CharField(max_length=20, null=True, blank=True)

    class Meta:
        ordering = ['-request_datetime']

    def __str__(self):
        return "Friend request from " + self.request_from.user.username + " to " + self.request_to.user.username

class GameParticipationRequest(models.Model):
    request_from = models.ForeignKey(Player, on_delete=models.CASCADE)
    request_to_game = models.ForeignKey(Game, on_delete=models.CASCADE)
    request_datetime = models.DateTimeField()
    action_taken_datetime = models.DateTimeField(null=True, blank=True)
    state = models.CharField(max_length=20, null=True, blank=True)

    class Meta:
        ordering = ['-request_datetime']

    def __str__(self):
        return "Game participation request from " + self.request_from.user.username + " to " + self.request_to_game.name

game_planner_app/views.py
import json

from django.conf import settings
from django.core.serializers import serialize
from django.core.serializers.json import DjangoJSONEncoder
from django.shortcuts import redirect, render, get_object_or_404
from django.http import HttpResponse, HttpResponseForbidden, HttpResponseNotFound, JsonResponse
from django.views import generic
from django.forms.models import model_to_dict
from django.utils import timezone

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

from datetime import date, datetime

from game_planner_api.models import Player, Game, Notification, Friendship, GameParticipationRequest, NotificationType
from .forms import SignUpForm, LoginForm, CreateGameForm, ManageProfileForm, ManageGameForm

def index(request):
    params = {'user': request.user}

    if request.user.is_authenticated:
        notifications = Notification.objects.filter(user=request.user, read=False)
        params['notifications'] = notifications

    return render(request, 'game_planner_app/index.html', params)

def login_view(request):
    if request.user.is_authenticated:
        return redirect('game_planner_app:index')

    next = ""
    if request.GET:
        next = request.GET['next']

    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            login(request, user)

            # redirect to correct page if there is a next arg
            if next == "":
                return redirect('game_planner_app:index')
            else:
                return redirect(next)
    else:
        form = LoginForm()
    return render(request, 'game_planner_app/login.html', {'form': form})

def logout_view(request):
    # TODO if no user is currently logged in, display message saying that
    logout(request)
    return redirect('game_planner_app:index')

def signup(request):
    if request.user.is_authenticated:
        return redirect('game_planner_app:index')
        
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('game_planner_app:index')
    else:
        form = SignUpForm()
    return render(request, 'game_planner_app/signup.html', {'form': form})

@login_required
def manage_profile(request):
    if request.method == 'POST':
        form = ManageProfileForm(request.POST, user=request.user)
        if form.is_valid():
            update_session_auth_hash(request, form.user)
            return redirect('game_planner_app:profile', pk=request.user.id)
    else:
        form = ManageProfileForm()
    return render(request, 'game_planner_app/manage_profile.html', {'form': form})

@login_required
def create_game(request):
    if request.method == 'POST':
        form = CreateGameForm(request.POST, user=request.user)
        if form.is_valid():
            form.save()
            return redirect('game_planner_app:game_detail', pk=form.pk)
    else:
        form = CreateGameForm()
    return render(request, 'game_planner_app/create_game.html', {'form': form})

@login_required
def manage_game(request, pk):

    if request.GET and request.GET['notif_id']:
        notification_read_common(request.user, request.GET['notif_id'])

    game = get_object_or_404(Game, pk=pk)
    is_admin = (request.user == game.admin)

    participation_requests = GameParticipationRequest.objects.filter(request_to_game=game, state__isnull=True)
    
    if is_admin:

        if request.method == 'POST':
            form = ManageGameForm(request.POST, game=game)
            if form.is_valid():
                return redirect('game_planner_app:game_detail', pk=pk)
        else:
            form = ManageGameForm()
        
        return render(request, 'game_planner_app/manage_game.html', {'form': form, 'participation_requests': participation_requests})

    else:
        return HttpResponseForbidden()
        
class GamesListView(generic.ListView):
    model = Game
    template_name = "game_planner_app/games.html"
    context_object_name = 'games'

    def get_queryset(self):
        """
        Excludes any games that aren't administered by the logged in user.
        """
        qs = super().get_queryset()

        user = self.request.user
        # Get player's games list
        player = Player.objects.get(user=user)

        games_dictionary = {}

        games_dictionary['administered'] = qs.filter(admin=user)
        games_dictionary['invited'] = qs.filter(players=player)
        games_dictionary['public'] = qs.filter(private=False)

        return games_dictionary
    
class PlayersListView(generic.ListView):
    model = Player
    template_name = "game_planner_app/players.html"
    context_object_name = 'players'

    def get_queryset(self):
        qs = super().get_queryset()
        players = qs

        # Excludes logged in user from player list
        user = self.request.user
        if self.request.user and self.request.user.is_authenticated:
            players = qs.exclude(user=user)
        
        return players

def game_detail(request, pk):
    game = get_object_or_404(Game, pk=pk)

    if request.user and request.user.is_authenticated:
        player = Player.objects.get(user=request.user)
        is_admin = (request.user == game.admin)
        authorized = (player in game.players.all()) or is_admin or not game.private

        participating = (player in game.players.all()) or is_admin

        active_participation_request = GameParticipationRequest.objects.filter(request_from=player, request_to_game=game, state__isnull=True)

        return render(request, 'game_planner_app/game_detail.html', {'game': game,
                                                                 'authorized': authorized,
                                                                 'is_admin': is_admin,
                                                                 'participating': participating,
                                                                 'active_participation_request': active_participation_request})
    
    else:
        return render(request, 'game_planner_app/game_detail.html', {'game': game})

class ProfileView(generic.DetailView):
    model = User
    template_name = 'game_planner_app/profile.html'
    context_object_name = 'profile_user'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Get Player object
        player = Player.objects.get(user=self.object)

        if self.request.user.is_authenticated:
            # Add authenticated user to context if user is currently logged in
            context['request_user'] = self.request.user

            # Add players friends list to context if user is currently logged in
            request_player = Player.objects.get(user=self.request.user)

            # Add are_friends flag to context
            context['are_friends'] = player in list(request_player.friends.all())

            # Check if there's an existing active outgoing request
            outgoing_request = Friendship.objects.filter(request_from=request_player, request_to=player, state__isnull=True)
            context['outgoing_request'] = outgoing_request

            # Check if there's an existing active incoming request
            incoming_request = Friendship.objects.filter(request_from=player, request_to=request_player, state__isnull=True)
            context['incoming_request'] = incoming_request

            # Add games list containing: public games, games authenticated user is also invited to, games authenticated user is admin
            games = Game.objects.filter(players=player, private=False) \
                                    | Game.objects.filter(players=player).filter(players=request_player) \
                                    | Game.objects.filter(players=player, admin=self.request.user)
            games = games.distinct()

        else:
            # Add public games
            games = Game.objects.filter(players=player, private=False)

        context['past_games'] = games.filter(when__lte=timezone.now())
        context['upcoming_games'] = games.filter(when__gt=timezone.now())
        
        # Add profile player to context
        context['player'] = player

        # Add profile player friends list to context
        context['friends_list'] = list(player.friends.all()) 
        
        return context

def notification_read_common(user, notification_id):
    notification = Notification.objects.get(pk=notification_id)

    if notification.user == user and notification.read == False:
        notification.read = True
        notification.read_datetime = timezone.now()
        notification.save()
        
        return True
    else:
        return False

@login_required
def notification_read(request):
    request_json = json.loads(request.body)
    notification_id = request_json['notification_id']

    result = notification_read_common(request.user, notification_id)

    if(result):
        return HttpResponse("OK")
    else:
        return HttpResponseNotFound()

@login_required
def mark_all_as_read(request):
    unread_notifications = Notification.objects.filter(user=request.user,
                                                    read=False)
    
    success = True

    for notif in unread_notifications:
        success = notification_read_common(request.user, notif.id)

    if(success):

game_planner_app/templates/game_planner_app/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/51738b8e2d.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'game_planner_app/style.css' %}">
    <script>
        var csrftoken = '{{ csrf_token }}';
    </script>
    <script src="{% static 'game_planner_app/script.js' %}"></script>

    <title>{% block title %}Game planner: plan games with friends{% endblock %}</title>

    {% if user.is_authenticated %}
    <nav class="navbar fixed-top navbar-expand-sm navbar-dark bg-primary">
        <!-- "Game Planner" link to index -->
        <a class="navbar-brand" href="{% url 'game_planner_app:index' %}">Game Planner</a>

        <!-- Links to Players, Games, and Create Game button -->
        <div class="collapse navbar-collapse order-3 order-sm-2" id="navbarNavDropdown">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'game_planner_app:players' %}">Players</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'game_planner_app:games' %}">Games</a>
                </li>
                <a class="btn btn-outline-light" href="{% url 'game_planner_app:create_game' %}">Create Game</a>
            </ul>
        </div>

        <div class="d-flex flex-row order-2 order-sm-3">
            <!-- Collapse button -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown">
                <span class="navbar-toggler-icon"></span>
            </button>

            <!-- Friends icon -->
            <div class="nav-item dropdown">
                <a class="nav-link px-2 position-relative" id="friendsDropdown" role="button" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-user-friends" style="color:rgb(158, 206, 217);"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right default-top-spacer" aria-labelledby="friendsDropdown">
                    <span class="dropdown-header">Social</span>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'game_planner_app:friend_requests' %}">Friend Requests</a>
                    <a class="dropdown-item" href="{% url 'game_planner_app:players' %}">Find Players</a>
                </div>
            </div>

            <!-- Notification bell -->
            <div class="nav-item dropdown">
                <!-- bell icon -->
                <a class="nav-link px-2 position-relative" onclick="get_notifications()" id="notificationsDropdown"
                    role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-bell" style="color:rgb(158, 206, 217);"></i>
                </a>
                <!-- dropdown box -->
                <div class="dropdown-menu notify-drop dropdown-menu-right default-top-spacer"
                    aria-labelledby="notificationsDropdown">
                    <div class="notify-drop-title">
                        <div class="row">
                            <!-- "Notifications" title text -->
                            <div class="col-md-6 col-sm-6 col-xs-6">Notifications</div>
                            <!-- Mark all as read icon -->
                            <div class="col-md-6 col-sm-6 col-xs-6 text-right">
                                <a href="" onclick="mark_all_as_read()" title="Mark all as read.">
                                    <i class="far fa-check-circle"></i>
                                </a>
                            </div>
                        </div>
                    </div>

                    <div class="drop-content" id="notificationsDropdownContent">
                        <!-- Loading icon while request is made -->
                        <div id="notificationDropdownLoadingSpinner"
                            class="d-flex justify-content-center half-top-spacer">
                            <div class="spinner-border spinner-border-sm" role="status">
                                <span class="sr-only">Loading...</span>
                            </div>
                        </div>

                    </div>
                </div>
            </div>

            <!-- Profile icon -->
            <div class="nav-item dropdown default-right-spacer">
                <a class="nav-link px-2 position-relative" id="profileDropdown" role="button" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-user" style="color:rgb(158, 206, 217);"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right default-top-spacer" aria-labelledby="profileDropdown">
                    <span class="dropdown-header">{{ user.username }}</span>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'game_planner_app:profile' user.pk %}">Profile</a>
                    <a class="dropdown-item" href="{% url 'game_planner_app:manage_profile' %}">Manage Profile</a>
                </div>
            </div>

            <!-- Logout button -->
            <a class="btn btn-outline-light" href="{% url 'game_planner_app:logout' %}">Logout</a>

        </div>
    </nav>
    {% else %}
    <nav class="navbar sticky-top navbar-expand-sm navbar-dark bg-primary">
        <a class="navbar-brand" href="{% url 'game_planner_app:index' %}">Game Planner</a>

        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'game_planner_app:players' %}">Players</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'game_planner_app:games' %}">Games</a>
                </li>
            </ul>
        </div>

        <!-- Signup and Login buttons -->
        <div class="float-right">
            <a class="btn btn-light" href="{% url 'game_planner_app:signup' %}">Signup</a>
            <a class="btn btn-outline-light" href="{% url 'game_planner_app:login' %}">Login</a><br>
        </div>
    </nav>
    {% endif %}
</head>

<body>
    <div id="content" class="navbar-top-spacer default-left-spacer">
        {% block content %}
        
        {% endblock %}
    </div>
</body>

</html>

game_planner_app/templates/game_planner_app/create_game.html
{% extends "base.html" %}

{% block content %}

<h2>Create Game</h2>

<form method="post">

    {% csrf_token %}

    {% for field in form %}
    <p>
        {{ field.label_tag }}<br>
        {{ field }}

        {% if field.help_text %}
        <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}

        {% for error in field.errors %}
        <p style="color: red">{{ error }}</p>
        {% endfor %}
    </p>
    {% endfor %}

    <button type="submit">Create game</button>
</form>

{% endblock %}

game_planner_app/templates/game_planner_app/friend_requests.html
{% extends "base.html" %}

{% block content %}

<h3>Friend requests</h3>

<ul>
    {% for friend_request in friend_requests %}
    <li>
        <a href="{% url 'game_planner_app:profile' friend_request.request_from.user.id %}">{{ friend_request.request_from }}</a>
        <button onclick="send_request('PATCH', '/api/friendships/{{ friend_request.pk }}', {'action': 'accept'})">Confirm</button>
        <button onclick="send_request('PATCH', '/api/friendships/{{ friend_request.pk }}', {'action': 'decline'})">Delete</button>
    </li>
    {% endfor %}
</ul>

{% endblock %}

game_planner_app/templates/game_planner_app/game_detail.html
{% extends "base.html" %}

{% block content %}

{% if authorized %}

    <p>Game Name: {{ game.name }}</p>
    <p>Admin: {{ game.admin }}</p>

    {% if is_admin %}
        <a href="{{ game.get_manage_url }}">Manage Game</a><br>
    {% endif %}

    {% if game.players.all %}
        <p>Players:</p>
        <ul>
            {% for player in game.players.all %}
                <li><a href="{{ player.get_absolute_url }}">{{ player.user.username }}</a></li>
            {% endfor %}
        </ul>
    {% endif %}

    {% if not participating and not active_participation_request %}

        <button onclick="send_request('POST', '/manage_participation/', {'action': 'request_participation', 'pk': '{{ game.game_id }}'})">Request participation</button>

    {% elif active_participation_request %}

        {% for participation_request in active_participation_request %}
            
            <button onclick="send_request('POST', '/manage_participation/', {'state': 'cancel', 'pk': '{{ participation_request.pk }}'})">Cancel participation request</button>

        {% endfor %}
        
    {% endif %}

{% elif not game.private %}

    <p>Game Name: {{ game.name }}</p>
    <p>Admin: {{ game.admin }}</p>

    {% if game.players.all %}
        <p>Players:</p>
        <ul>
            {% for player in game.players.all %}
                <li><a href="{{ player.get_absolute_url }}">{{ player.user.username }}</a></li>
            {% endfor %}
        </ul>
    {% endif %}

{% else %}
    <p>You're not invited to this private game.</p>
{% endif %}

{% endblock %}

game_planner_app/templates/game_planner_app/games.html
{% extends "base.html" %}

{% block content %}

{% if games.administered %}
<p>Games you are administering:</p>

<ul>
    {% for game in games.administered %}
    <li><a href="{{ game.get_absolute_url }}">{{ game.name }}</a></li>
    <a href="{{ game.get_manage_url }}">Manage Game</a><br>
    <p></p>
    {% endfor %}
</ul>
{% endif %}

{% if games.public %}
<p>Public games:</p>

<ul>
    {% for game in games.public %}
    <li><a href="{{ game.get_absolute_url }}">{{ game.name }}</a></li>
    {% endfor %}
</ul>
{% endif %}

{% if games.invited %}
<p>Games you are invited to:</p>

<ul>
    {% for game in games.invited %}
    <li><a href="{{ game.get_absolute_url }}">{{ game.name }}</a></li>
    {% endfor %}
</ul>
{% endif %}

{% if not games.administered and not games.public %}
<p>You currently don't have any games.</p>
{% endif %}

{% endblock %}

game_planner_app/templates/game_planner_app/index.html
{% extends "base.html" %}

game_planner_app/templates/game_planner_app/login.html
{% extends "base.html" %}

{% block content %}

<h2>Log in</h2>

<form method="post">
    {% csrf_token %}

    <div class="fieldWrapper">
        {{ form.username.errors }}
        <label for="{{ form.username.id_for_label }}">Username or email address:</label><br>
        {{ form.username }}
    </div>

    <div class="fieldWrapper">
        {{ form.password.errors }}
        <label for="{{ form.password.id_for_label }}">Password:</label><br>
        {{ form.password }}
    </div>
    <br>
    <button type="submit">Log in</button>
</form>

{% endblock %}

game_planner_app/templates/game_planner_app/manage_game.html
{% extends "base.html" %}

{% block content %}

<h2>Manage Game</h2>

<form method="post">
    {% csrf_token %}

    {% for field in form %}
    <p>
        {{ field.label_tag }}<br>
        {{ field }}

        {% if field.help_text %}
        <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}

        {% for error in field.errors %}
        <p style="color: red">{{ error }}</p>
        {% endfor %}
    </p>
    {% endfor %}

    <button type="submit">Update Game</button>
</form>

{% if participation_requests %}
<p>Game Participation Requests:</p>
<ul>
    {% for participation_request in participation_requests %}
    <li>
        <a href="{% url 'game_planner_app:profile' participation_request.request_from.user.id %}">{{ participation_request.request_from }}</a>
        <button onclick="send_request('POST', '/manage_participation/', {'state': 'accepted', 'pk': '{{ participation_request.pk }}'})">Add to Game</button>
        <button onclick="send_request('POST', '/manage_participation/', {'state': 'declined', 'pk': '{{ participation_request.pk }}'})">Delete</button>
    </li>
    {% endfor %}
</ul>
{% endif %}

{% endblock %}

game_planner_app/templates/game_planner_app/manage_profile.html
{% extends "base.html" %}

{% block content %}

<h2>Manage Profile</h2>

<form method="post">
    {% csrf_token %}

    {% for field in form %}
    <p>
        {{ field.label_tag }}<br>
        {{ field }}

        {% if field.help_text %}
        <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}

        {% for error in field.errors %}
        <p style="color: red">{{ error }}</p>
        {% endfor %}

    </p>
    {% endfor %}

    <button type="submit">Update Profile</button>
</form>

{% endblock %}

game_planner_app/templates/game_planner_app/profile.html
{% extends "base.html" %}

{% block content %}

<p>Username: {{ profile_user.username }}</p>
<p>First Name: {{ profile_user.first_name }}</p>
<p>Last Name: {{ profile_user.last_name }}</p>

{% if request_user == profile_user  %}

    <p>Email: {{ profile_user.email }}</p>
    <a href="{% url 'game_planner_app:manage_profile' %}">ManageProfile</a><br>

{% elif request_user %}

    {% if are_friends %}

        <button onclick="send_request('PATCH', '/api/players/{{ profile_user.username }}', {'action': 'remove_friend'})">Remove Friend</button>

    {% else %}

        {% if not incoming_request and not outgoing_request %}
        
            <button onclick="send_request('POST', '/api/friendships', {'username': '{{ profile_user.username }}'})">Add Friend</button>

        {% elif incoming_request %}

            {% for friend_request in incoming_request %}

                <div>
                    <p>{{ profile_user.username }} has sent you a friend request.</p>
                    <button onclick="send_request('PATCH', '/api/friendships/{{ friend_request.pk }}', {'action': 'accept'})">Confirm</button>
                    <button onclick="send_request('PATCH', '/api/friendships/{{ friend_request.pk }}', {'action': 'decline'})">Delete</button>
                </div>

            {% endfor %}

        {% elif outgoing_request %}

            {% for friend_request in outgoing_request %}
            
                <div>
                    <button onclick="send_request('PATCH', '/api/friendships/{{ friend_request.pk }}', {'action': 'cancel'})">Cancel friend request</button>
                </div>

            {% endfor %}

        {% endif %}

    {% endif %}

{% endif %}

{% if friends_list %}

    <p>Friends:</p>

    <ul>
        {% for player in friends_list %}
            <li><a href="{{ player.get_absolute_url }}">{{ player }}</a></li>
        {% endfor %}
    </ul>

{% endif %}

{% if upcoming_games %}

    <p>Upcoming games:</p>

    <ul>
        {% for game in upcoming_games %}
            <li><a href="{{ game.get_absolute_url }}">{{ game }}</a></li>
        {% endfor %}
    </ul>

{% endif %}

{% if past_games %}

    <p>Past games:</p>

    <ul>
        {% for game in past_games %}
            <li><a href="{{ game.get_absolute_url }}">{{ game }}</a></li>
        {% endfor %}
    </ul>

{% endif %}

{% endblock %}